# Generated by Django 4.1.7 on 2023-05-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_bond_remove_enrollment_class_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowKnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Como soube ?')),
            ],
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='bond_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.bond', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_of_birth',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='rg',
            field=models.CharField(max_length=10, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='route',
            field=models.CharField(max_length=100, verbose_name='Qual trajeto você quer participar ?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='how_knew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.howknew', verbose_name='Como soube do evento?'),
        ),
    ]
