# Generated by Django 4.1.7 on 2023-05-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_howknew_alter_enrollment_bond_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Trajeto desejado'),
        ),
    ]
