# Generated by Django 4.1.7 on 2023-05-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_enrollment_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Evento', max_length=50, verbose_name='Nome do Evento'),
        ),
    ]
