# Generated by Django 4.1.7 on 2023-05-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='email',
            field=models.CharField(default=None, max_length=30, verbose_name='Email para contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='social_network',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Instagram'),
        ),
    ]
