# Generated by Django 4.1.7 on 2023-05-13 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0025_route_color'),
        ('event', '0018_remove_enrollment_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome do caminho')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.route')),
            ],
        ),
    ]
