# Generated by Django 4.1.7 on 2023-05-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_enrollment_route_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepath',
            name='time',
            field=models.CharField(default=None, max_length=10, verbose_name='Horário de Sáida'),
            preserve_default=False,
        ),
    ]
