# Generated by Django 4.1.7 on 2023-05-16 11:24

import cities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_routepath_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição do ponto')),
                ('iconUrl', models.FileField(upload_to='events/icons/%Y/%m/%d', validators=[cities.validators.validate_file_extension_category])),
                ('lat', models.CharField(max_length=20, verbose_name='Latitude do Ponto')),
                ('lng', models.CharField(max_length=20, verbose_name='Longitude do Ponto')),
                ('active', models.BooleanField(default=False, verbose_name='Estado do Ponto')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='routes',
        ),
        migrations.AddField(
            model_name='event',
            name='routes_data',
            field=models.ManyToManyField(blank=True, null=True, to='event.routepath', verbose_name='Rotas do Evento'),
        ),
        migrations.AddField(
            model_name='routepath',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Estado da Rota'),
        ),
        migrations.AddField(
            model_name='routepath',
            name='departure_location',
            field=models.CharField(default=None, max_length=50, verbose_name='Local de Partida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='points',
            field=models.ManyToManyField(blank=True, null=True, to='event.anchorpoint', verbose_name='Pontos do Evento'),
        ),
    ]
